name: Build and Email Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # Use your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Upload APK as artifact (optional)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # Send APK via email
      - name: Send email with APK
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "New Flutter Release APK"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          body: "Attached is the latest release APK build from the main branch."
          attachments: build/app/outputs/flutter-apk/app-release.apk
